### ISSUE TITLE
API: Datetime tz-aware/tz-naive ops consistency

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#11456]
Followings should be changed to coerce to ``object`` dtype.

## Coerce to tz-naive 

- [ ] Slice (``__getitem__``) resets tz  #11351 
- [ ] ``.loc`` assignment coerces to naive #11365
- [ ] ``GroupBy.first`` coerces to naive #10668 
- [ ] ``DataFrame.combine_first`` #10567

## Raises TypeError / ValueError

- [ ] ``DatetimeIndex.union`` raises ``TypeError`` #11351

## Bug

- [ ] ``Series.append`` raises ``AttributeError`` #11455
