### ISSUE TITLE
CLN & REORG core/common.py

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#12503]
some ideas on reorging.

- [X] rename ``pandas/util/misc.py`` to ``pandas/util/tools.py`` or ``pandas/util/util.py`` (https://github.com/pydata/pandas/commit/a69d628db77cc67f79590bbb3f13e178cb8b0e93)
  - [X] move ``core/generic.py/_validate_kwargs`` (and new ``validate_args``) here (https://github.com/pydata/pandas/commit/6e6478764a8e002e2436da3ee981512917d9b7c4)
  - [ ] move the ``various python utilities`` section from ``core/common``
- [x] create ``pandas/types/`` (#12804)
  - [x] move ``pandas/core/dtypes.py`` here
- [x] create ``pandas/types/types.py`` (#12804) 
  - [x] move ``bind_method``, ``create_pandas_abc_types`` here (from ``core/common.py``)
  - [ ] move the ``is_...._dtype`` to here
- [x] move ``core/common.py/concat*`` to new sub-package ``types/concat`` (#12844)
- [x] move ``core/common.py/take*`` stuff to ``algorithms`` (may need to create a sub-package for this) (#12804)
- [x] create new sub-package ``pandas/formats`` (#12804)
  - [x] move ``core/common.py/printing utilities`` to new sub-package ``pandas/formats/printing.py`` (#12804)
  - [x] move ``core/format.py`` here as well (maybe split later) (#12804)

**Comment by jreback** [comment]
cc @wesm

**Comment by gfyoung** [comment]
+1 for the reorganization.  Will move the `arg` and `kwarg` validators in their own separate module in my own PR (#12413)

**Comment by wesm** [comment]
+1 on anything that helps separate implementation matters, especially anything we're contemplating replacing / refactoring, from the public user API.
