### ISSUE TITLE
BUG: Series not correctly formatted in truncated output

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas#8532]
Overview of the issues:

- [ ] Number of rows is incorrect (#7508)
- [ ] Setting `pd.options.display.max_rows` to larger values has no effect (https://github.com/pydata/pandas/issues/7508#issuecomment-58669898)
- [ ] formatting seems to occur seperately for both parts (this issue #8532, see two exaples below)

----

When a Series gets truncated, it seems that both parts are formatted separately, with the consequence that eg:

- the float formatting can be different in both parts
- the alignment (depending on the width of the index) is different in both parts

Note that this is not the case with a DataFrame

```
In [44]: s = pd.Series([1,1,1,1,1,1,1,1,1,1,0.9999,1,1]*10)

In [45]: pd.options.display.max_rows = 10

In [46]: s
Out[46]:
0    1
1    1
2    1
...
127    0.9999
128    1.0000
129    1.0000
Length: 130, dtype: float64

In [47]: s.to_frame()
Out[47]:
          0
0    1.0000
1    1.0000
2    1.0000
3    1.0000
4    1.0000
..      ...
125  1.0000
126  1.0000
127  0.9999
128  1.0000
129  1.0000

[130 rows x 1 columns]
```
