### ISSUE TITLE
StringMethods should have the same methods as standard str

### ISSUE THREAD

**Issue by sinhrks** [pydata/pandas#9111]
Should `StringMethods` be compatible with standard `str`, or have only useful methods? Sometimes I have to adjust text formats before converting other types, and I've chosen additionals which makes formatting / adjustments easier. Any ideas?

- [x] `str.find` (#9386)
- [x] `str.rfind` (#9386)
- [x] `str.isalnum` (#9282)
- [x] `str.isalpha` (#9282)
- [x] `str.isdigit` (#9282)
- [x] `str.isspace` (#9282)
- [x] `str.islower` (#9282)
- [x] `str.isupper` (#9282)
- [x] `str.istitle` (#9282)
- [x] `str.ljust` (#9352)
- [x] `str.rjust` (#9352): `StringMethods.pad` works as the same as `ljust`, `rjust` and `center` by switching `side` option. And `StringMethods.center` exists, `ljust` and `rjust` don't.
- [x] `str.rsplit`: ``split`` also supports regex, and there seems no straightforward way to ``rsplit`` using regex. (#10303)
- [x] `str.zfill` (#9387)
- [x] `StringMethods.center` and `StringMethods.pad` should have 'fillchar` kw to specify padding character.  (#9352)
- [x] `str.capitalize` (#9766)
- [x] `str.swapcase` (#9766)
- [x] `str.translate` (#10052)
- [x] `str.index` (#10045)
- [x] `str.rindex` (#10045)
- [x] `str.partition` (#9773)
- [x] `str.rpartition` (#9773)

- [x] `unicode.isnumeric` (#9439)
- [x] `unicode.isdecimal` (#9439)
- [x] ``unicodedata.normalize`` (#10031)

**NOTE** For python 2.x, once convert target to unicode internally then call the func.    

## Which may not be very userful:
- ``expandtabs``
- ``splitlines``

I think there is an option to implement these to say "support the same methods as standard ``str``".

**Comment by sinhrks** [comment]
Added `unicode.isnumeric` and `unicode.isdecimal` to the list. 

- https://docs.python.org/2/library/stdtypes.html#unicode.isnumeric

**Comment by sinhrks** [comment]
Would like to discuss an additional:

- Unicode normalization

  [`unicodedata.normalize`](https://docs.python.org/2/library/unicodedata.html?highlight=unicodedata#unicodedata.normalize) is quite useful to standardize multi-bytes characters. I think it is nice if `StringMethods.normalize` can perform this.

  ```
  import pandas as pd
  s = pd.Series([u'ＡＢＣＤＥ', u'１２３４５'])
  s
  # 0    ＡＢＣＤＥ
  # 1    １２３４５
  # dtype: object

  s.str.normalize()
  # 0    ABCDE
  # 1    12345
  # dtype: object
  ```

**Comment by sinhrks** [comment]
The last remaining is ``str.rsplit``. Even though ``split`` supports both ``str`` and regex, I think there is no easy way (and use case) to ``rsplit`` with ``regex``. How about implement ``str.rsplit`` only for ``str`` and closig this.

CC @mortada

**Comment by mortada** [comment]
@sinhrks that sounds reasonable. I'm happy to do a PR for this.

**Comment by jreback** [comment]
looks like this is finished!

awesome job @sinhrks, cc @mortada

**Comment by sinhrks** [comment]
Thanks, @mortada !
