### ISSUE TITLE
CLN: make sure that we don't have extraneous imports

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#9482]
xref #9394 
xref #7282 

``numexpr/bottleneck`` are ok by default

you can check with something like this:

```
[jreback-~/pandas] python -v -c 'import pandas' > & out
[jreback-~/pandas] grep 'import ' out | more
```
- [x] ~~``matplotlib`` (not sure if this is possible to remove by default)~~ The converters are set, not so easy to remove.
- [x] ``io/packers.py`` imports ``blosc`` and possibly other things, #9482
- [x] ``io/gbq.py`` import a lot of things (e.g. ``apiclient/googleapiclient/oauth2client/gflags``), #9482
- [x] ~~``xlsxwriter``~~ this is set in ``core/config_init.py`` for the default engine. Not easy to remove.
- [x] ``html5lib/bs4`` (from ``io/html.py``), #9482

These should be done on first usage of the library, and not on general import
like in ``io/pytables.py`` (e.g. the ``_tables()``) call.

**Comment by jreback** [comment]
@cpcloud can you fix the html imports?
